name: esu
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+13
#version: 1.0.3+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  auto_size_text: ^3.0.0
  #  cache online images
  cached_network_image: ^3.2.1
  #  equatable objects
  equatable: ^2.0.3
  #validation
  form_field_validator: ^1.1.0
  #getx
  get: ^4.6.5
  #shared preference
  shared_preferences: ^2.0.15
  #injection
  get_it: ^7.2.0
  injectable: ^1.5.3
  #internect checker
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.5
  #permissions
  permission_handler: ^9.2.0
  #loading progress indicator
  modal_progress_hud_nsn: ^0.2.1
  #svg
  flutter_svg: ^1.1.0
  # toast for user
  fluttertoast: ^8.0.9
  #  responsive screen
  flutter_screenutil: ^5.4.0+1
  # model creation
  json_serializable: ^6.2.0
  # network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  #  file picker
  file_picker: ^5.0.1
  # image picker
  image_picker: ^0.8.4+13
  url_launcher: ^6.1.2
  dartz: ^0.10.1
  # UI
  lottie: ^1.3.0
  expandable: ^5.0.1
  html: ^0.15.0
  # Pdf viewer
  syncfusion_flutter_pdfviewer: ^20.1.57-beta
  #firebase
  firebase_core: ^1.22.0
  firebase_messaging: ^12.0.1
  firebase_crashlytics: ^2.8.7
  firebase_analytics: ^9.3.1
  #  firebase_remote_config: ^2.0.8
  flutter_local_notifications: ^9.6.0
  # date format
  intl: ^0.17.0
  #  video player
  youtube_player_flutter: ^8.1.0
  webview_flutter: ^3.0.4
  flutter_html:
    git:
      url: https://github.com/Sub6Resources/flutter_html.git
      ref: master

  # files
  flutter_downloader: ^1.7.4
  open_filex: ^4.1.1
  path_provider: ^2.0.11
  # local DB
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  # search
  search_page: ^2.0.0+1
  # app info
  package_info_plus: ^1.4.2
  # control app badge
  flutter_app_badger: ^1.4.0
  #  Pick location
  google_maps_flutter: ^2.1.10
  map_picker: ^0.0.3
  geocoding: ^2.0.4
  location: ^4.4.0
  geolocator: ^8.2.0
  # open setting
  app_settings: ^4.1.8
  # progress indicator
  percent_indicator: ^4.2.2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.10.0
  flutter_gen_runner: ^4.2.1
  flutter_lints: ^2.0.1
  flutter_flavorizr: ^2.1.5
  json_annotation: ^4.6.0
  injectable_generator:
  json_serializable: ^6.2.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/src/
  line_length: 120

  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: din
      fonts:
        - asset: fonts/din.ttf

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    prod:
      app:
        name: "ESU"

      android:
        applicationId: "com.sis.esu"
        firebase:
          config: "./firebase/prod/google-services.json"

      ios:
        bundleId: "com.sis.esu"
        firebase:
          config: "./firebase/prod/GoogleService-Info.plist"

    dev:
      app:
        name: "ESU Dev"
      android:
        applicationId: "com.sis.esu.dev"
        firebase:
          config: "./firebase/dev/google-services.json"

      ios:
        bundleId: "com.sis.esu.dev"
        firebase:
          config: "./firebase/dev/GoogleService-Info.plist"

    midocean:
      app:
        name: "Midocean"
      android:
        applicationId: "com.sis.midocean.edu"
        firebase:
          config: "./firebase/midocean/google-services.json"

      ios:
        bundleId: "com.sis.midocean.edu"
        firebase:
          config: "./firebase/midocean/GoogleService-Info.plist"
