name: boilerplate
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  auto_size_text: ^3.0.0
  #  cache online images
  cached_network_image: ^3.2.1
  #  equatable objects
  equatable: ^2.0.3
  #validation
  form_field_validator: ^1.1.0
  #getx
  get: ^4.6.5
  #shared preference
  shared_preferences: ^2.0.15
  #injection
  get_it: ^7.2.0
  #internect checker
  internet_connection_checker: ^0.0.1+4
  #permissions
  permission_handler: ^9.2.0
  #loading progress indicator
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  #svg
  flutter_svg: ^1.1.0
  # toast for user
  fluttertoast: ^8.0.9
  #  responsive screen
  flutter_screenutil: ^5.4.0+1
  # model creation
  json_serializable: ^6.2.0
  # network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  #  file picker
  file_picker: ^4.6.1
  # image picker
  image_picker: ^0.8.5+3
  country_picker: ^2.0.15
  url_launcher: ^6.1.2
  dartz: ^0.10.1
  # UI
  lottie: ^1.3.0
  expandable: ^5.0.1
  html: ^0.15.0
  # Pdf viewer
  syncfusion_flutter_pdfviewer: ^20.1.57-beta
  #firebase
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  firebase_remote_config: ^2.0.8
  flutter_local_notifications: ^9.6.0
  # date format
  intl: ^0.17.0
  #  video player
  video_player: ^2.4.2
  flutter_stripe: ^3.0.2
  flutter_html:
    git:
      url: https://github.com/Sub6Resources/flutter_html.git
      ref: master
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_gen_runner: ^4.2.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/src/
  line_length: 120

  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_icon_bg.jpeg'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: din
      fonts:
        - asset: fonts/din.ttf
